version: "3.12"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 portfolio.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: portfolio.settings
