# Generated by Django 5.0.6 on 2024-07-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_alter_contact_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.CharField(default='not-found', max_length=200),
            preserve_default=False,
        ),
    ]
