# Generated by Django 5.0.6 on 2024-07-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_skillcategory_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='tag',
            field=models.CharField(default='cs', max_length=100),
            preserve_default=False,
        ),
    ]
