# Generated by Django 5.1.2 on 2024-10-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_project_technologies_used'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
